# Whether to restore player data (inventory, experience, location, ...) after the game ended
storePlayerData: true

# Countdown (in seconds)
countdown:
  lobby: 20
  start: 10

loot:
  # Delay until loot starts to drop (seconds)
  delay: 20

  # Interval of loot drops (seconds)
  interval: 60

end:
  # Delay after the game ended until players are sent back
  delay: 5

items:
  knife:
    type: "DIAMOND_AXE" #Don't change this, unless you have a custom resource pack
    meta:
      display: "&c&lKnife"
      enchants:
      - "DAMAGE_ALLx8-f"
  gun:
    type: "DIAMOND_HOE" #Don't change this, unless you have a custom resource pack
    meta:
      display: "&9&l"
  bullet:
    type: "ARROW" #Don't change this, unless you have a custom resource pack
    meta:
      display: "&8Bullet"
  loot:
    type: "DIAMOND" #Don't change this, unless you have a custom resource pack
  nameInfo:
    type: "NAME_TAG"
    meta:
      display: "%s" #%s gets replaced by the player's nametag
      enchants:
      - "DURABILITYx1-f"
  speedBoost:
    type: "SUGAR"
    meta:
      display: "&7Speed Boost"
  teleporter:
    type: "COMPASS"
    meta:
      display: "&7Teleporter"

resourcepack:
  game:
    url: "https://download.nodecdn.net/containers/nodecraft/minepack/868476a4a838f7e0c8522bc0223ddd24.zip"
    hash: "890e14df06c2f5f187e3b725ceaaa106ebf1f650"
  reset:
    url: "https://download.nodecdn.net/containers/nodecraft/minepack/d2c7e3ec1f6fae1a3893a52ac4f2a13b.zip"
    hash: "5b056fdb71892731fc15fd05ce0329ef251ca3f1"

messages:
  role:
    default:
      name: "&9Bystander"
      title: "&9You are a ${role.default.name}"
      subtitle: ""
      objective: "&e&lSurvive &e&land try to find out who the &c&lMurderer &e&lis!"
      bossbar:
        text: "%s                ${role.default.name}"
        color: "BLUE"
        style: "PROGRESS"
    murderer:
      name: "&cMurderer"
      title: "&cYou are the ${role.murderer.name}"
      subtitle: ""
      objective: "&e&lKill all &9&lBystanders&e&l, but don't act suspicious!"
      bossbar:
        text: "%s                ${role.murderer.name}"
        color: "RED"
        style: "NOTCHED_10"
    weapon:
      name: "&9Bystander"
      title: "${role.default.title}"
      subtitle: "&9with a secret weapon"
      objective: "&e&lFind the &c&lMurderer &e&land kill them with your &9&lsecret Weapon&e!"
      bossbar:
        text: "%s                ${role.weapon.name}"
        color: "BLUE"
        style: "NOTCHED_10"
    spectator:
      name: "&7Spectator"
  game:
    state:
      waiting:
        sign: "&a[Waiting]"
      lobby:
        sign: "&a[Lobby]"
      starting:
        sign: "&c[Starting]"
      started:
        sign: "&c[Ingame]"
      ended:
        sign: "&7[Ended]"
    join: "&7%s &ejoined the game. &6(%s/%s)"
    leave: "&7%s &eleft the game. &6(%s/%s)"
    countdown:
      lobby:
        time: "&eLobby ends in %s seconds"
        cancel: "&cNot enough players, coundown cancelled"
      start:
        time: "&eGame starts in %s seconds"



# Name tags and colors - color+name can only be 15 characters long!
name:
  tags:
  - "Alfa"
  - "Bravo"
  - "Charlie"
  - "Delta"
  - "Echo"
  - "Foxtrot"
  - "Gold"
  - "Hotel"
  - "India"
  - "Juliett"
  - "Kilo"
  - "Lima"
  - "Miko"
  - "November"
  - "Oscar"
  - "Papa"
  - "Quebec"
  - "Romeo"
  - "Sierra"
  - "Tango"
  - "Uniform"
  - "Victor"
  - "X-Ray"
  - "Yankee"
  - "Zulu"
  colors:
  - "&1"
  - "&2"
  - "&3"
  - "&4"
  - "&5"
  - "&6"
  - "&7"
  - "&8"
  - "&9"
  - "&a"
  - "&b"
  - "&c"
  - "&d"
  - "&e"

debug: false