name: Murder
main: org.inventivetalent.murder.Murder
author: inventivetalent
version: ${project.version}

softdepend: [PacketListenerApi, ItemBuilder, MessageBuilder, NPCLib, ResourcePackApi, TitleAPI]

commands:
  murder:
    aliases: []